### ISSUE TITLE
Comment Only: You have done a very nice job on this

### ISSUE THREAD

**Issue by Philliec459** [abhishekdbihani/synthetic_well-log_polynomial_regression#2]

**Comment by abhishekdbihani** [comment]
Thank you so much! Did you try out on some other well log?

**Comment by Philliec459** [comment]
Hi Abhishek,


I literally just downloaded your project a few minutes ago, loaded all of the required packages and ran your program with ease. Nice job. 

I will be studying your code further to implement and better understand your approach.  I am a practicing Petrophysicist with over 40 years of experience, but learning every day. I will study your discussion and code further in the next few days. As Petrophysicists we are always trying to predict log curves that are not originally furnished on all wells, and your project is great. It is work like this that is allowing us to fill in the gaps. In addition, your project is very helpful in keeping us old guys up-to-date with current technology. Thank you. 





Best Regards, 
 
_______________________________
 
E. Craig Phillips
CEO and Chief Petrophysicist
Crested Butte Petrophysical Consultants
 







459 Cisneros Lane
Crested Butte, CO 81224
USA
Office: +1 970-343-0730
Mobile: +1 970-343-0730
email: craig@cbpetro.com
Website: www.cbpetro.com
GitHub: https://github.com/Philliec459



The information contained in this electronic message is confidential, it constitutes a profesional and/or industrial secret in terms of the current legislation, and is intended for its recipient only. If you receive this message by mistake or if you are not the recipient thereof, please notify the sender and destroy it.

La informacion contenida en este mensaje de datos es confidencial, constituye un secreto industrial y/o profesional en terminos de la legislacion vigente y se encuentra dirigida exclusivamente al destinatario indicado en dicho mensaje. Si usted recibe esta informacion por error o si usted no es el destinatario del mensaje, favor de notificar al emisor, y destruyalo.

On Sep 7, 2020, at 6:56 PM, Abhishek Bihani <notifications@github.com> wrote:


Thank you so much! Did you try out on some other well log?
